import type { JsonValue, OpenApiSchema } from "./openapi-model";
import type { SchemaNode } from "./schema-graph";

export const GENERATED_HEADER =
  "// @generated by simtrain-sdk-generator. Do not edit.\n";

function referenceName(reference: string): string {
  const prefix = "#/components/schemas/";
  if (!reference.startsWith(prefix)) {
    throw new Error(`unsupported schema reference: ${reference}`);
  }
  return reference
    .slice(prefix.length)
    .replaceAll("~1", "/")
    .replaceAll("~0", "~");
}

function literal(value: JsonValue): string {
  return JSON.stringify(value);
}

function propertyName(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name);
}

function parenthesizeUnion(value: string): string {
  return value.includes(" | ") ? `(${value})` : value;
}

function docLines(schema: OpenApiSchema): readonly string[] {
  const lines: string[] = [];
  if (schema.description !== undefined) {
    lines.push(...schema.description.split(/\r?\n/));
  }
  if (schema.deprecated === true) lines.push("@deprecated");
  if (schema.format !== undefined) lines.push(`@format ${schema.format}`);
  if (schema.minimum !== undefined)
    lines.push(`@minimum ${String(schema.minimum)}`);
  if (schema.maximum !== undefined)
    lines.push(`@maximum ${String(schema.maximum)}`);
  if (schema.exclusiveMinimum !== undefined) {
    lines.push(`@exclusiveMinimum ${String(schema.exclusiveMinimum)}`);
  }
  if (schema.exclusiveMaximum !== undefined) {
    lines.push(`@exclusiveMaximum ${String(schema.exclusiveMaximum)}`);
  }
  if (schema.multipleOf !== undefined) {
    lines.push(`@multipleOf ${String(schema.multipleOf)}`);
  }
  if (schema.minLength !== undefined)
    lines.push(`@minLength ${String(schema.minLength)}`);
  if (schema.maxLength !== undefined)
    lines.push(`@maxLength ${String(schema.maxLength)}`);
  if (schema.minItems !== undefined)
    lines.push(`@minItems ${String(schema.minItems)}`);
  if (schema.maxItems !== undefined)
    lines.push(`@maxItems ${String(schema.maxItems)}`);
  if (schema.minProperties !== undefined) {
    lines.push(`@minProperties ${String(schema.minProperties)}`);
  }
  if (schema.maxProperties !== undefined) {
    lines.push(`@maxProperties ${String(schema.maxProperties)}`);
  }
  if (schema.pattern !== undefined) lines.push(`@pattern ${schema.pattern}`);
  if (schema.default !== undefined)
    lines.push(`@default ${literal(schema.default)}`);
  if (schema.example !== undefined)
    lines.push(`@example ${literal(schema.example)}`);
  if (schema.discriminator !== undefined) {
    lines.push(`@discriminator ${schema.discriminator.propertyName}`);
  }
  return lines;
}

function renderDoc(schema: OpenApiSchema, indentation = ""): string {
  const lines = docLines(schema);
  if (lines.length === 0) return "";
  return `${indentation}/**\n${lines
    .map(line => `${indentation} * ${line.replaceAll("*/", "*\\/")}`)
    .join("\n")}\n${indentation} */\n`;
}

function renderObject(schema: OpenApiSchema, indentation: string): string {
  const properties = Object.entries(schema.properties ?? {}).sort(
    ([left], [right]) => left.localeCompare(right)
  );
  const required = new Set(schema.required ?? []);
  let objectType: string;
  if (properties.length === 0) {
    objectType = "{}";
  } else {
    const childIndentation = `${indentation}  `;
    const body = properties
      .map(([name, property]) => {
        const doc = renderDoc(property, childIndentation);
        const optional = required.has(name) ? "" : "?";
        return `${doc}${childIndentation}${propertyName(name)}${optional}: ${renderSchemaType(property, childIndentation)};`;
      })
      .join("\n");
    objectType = `{\n${body}\n${indentation}}`;
  }

  if (schema.additionalProperties === true) {
    return properties.length === 0
      ? "Record<string, unknown>"
      : `${objectType} & Record<string, unknown>`;
  }
  if (
    schema.additionalProperties !== undefined &&
    schema.additionalProperties !== false
  ) {
    const map = `Record<string, ${renderSchemaType(schema.additionalProperties, indentation)}>`;
    return properties.length === 0 ? map : `${objectType} & ${map}`;
  }
  if (properties.length === 0) return "Record<string, unknown>";
  return objectType;
}

function renderBaseType(schema: OpenApiSchema, indentation: string): string {
  if (schema.enum !== undefined && schema.enum.length > 0) {
    return schema.enum.map(literal).join(" | ");
  }

  const intersections: string[] = [];
  if (schema.$ref !== undefined) intersections.push(referenceName(schema.$ref));
  if (schema.allOf !== undefined) {
    intersections.push(
      ...schema.allOf.map(child =>
        parenthesizeUnion(renderSchemaType(child, indentation))
      )
    );
  }
  const unionSchemas = schema.oneOf ?? schema.anyOf;
  if (unionSchemas !== undefined) {
    const union = unionSchemas
      .map(child => renderSchemaType(child, indentation))
      .join(" | ");
    const hasAnotherConstraint =
      intersections.length > 0 ||
      schema.type !== undefined ||
      schema.properties !== undefined ||
      schema.additionalProperties !== undefined;
    intersections.push(hasAnotherConstraint ? parenthesizeUnion(union) : union);
  }

  const hasObjectShape =
    schema.type === "object" ||
    schema.properties !== undefined ||
    schema.additionalProperties !== undefined;
  if (hasObjectShape) intersections.push(renderObject(schema, indentation));
  else if (schema.type === "array") {
    const item = schema.items
      ? renderSchemaType(schema.items, indentation)
      : "unknown";
    intersections.push(`${parenthesizeUnion(item)}[]`);
  } else if (schema.type === "string") intersections.push("string");
  else if (schema.type === "number" || schema.type === "integer") {
    intersections.push("number");
  } else if (schema.type === "boolean") intersections.push("boolean");

  if (intersections.length === 0) return "unknown";
  return intersections.join(" & ");
}

export function renderSchemaType(
  schema: OpenApiSchema,
  indentation = ""
): string {
  const base = renderBaseType(schema, indentation);
  return schema.nullable === true && base !== "null" ? `${base} | null` : base;
}

function canRenderInterface(schema: OpenApiSchema): boolean {
  return (
    schema.type === "object" &&
    schema.properties !== undefined &&
    schema.$ref === undefined &&
    schema.allOf === undefined &&
    schema.oneOf === undefined &&
    schema.anyOf === undefined &&
    schema.additionalProperties === undefined &&
    schema.nullable !== true &&
    schema.enum === undefined
  );
}

function renderNode(node: SchemaNode): string {
  const imports = node.references
    .filter(reference => reference !== node.name)
    .map(reference => `import type { ${reference} } from "./${reference}";`)
    .join("\n");
  const importBlock = imports ? `${imports}\n\n` : "";
  const doc = renderDoc(node.schema);
  if (canRenderInterface(node.schema)) {
    const object = renderObject(node.schema, "");
    const body = object.slice(1, -1).trim();
    return `${GENERATED_HEADER}\n${importBlock}${doc}export interface ${node.name} {\n${body}\n}\n`;
  }
  return `${GENERATED_HEADER}\n${importBlock}${doc}export type ${node.name} = ${renderSchemaType(node.schema)};\n`;
}

export function renderDtoFiles(
  graph: readonly SchemaNode[]
): ReadonlyMap<string, string> {
  const files = new Map<string, string>();
  for (const node of graph) {
    files.set(node.fileName, renderNode(node));
  }
  const barrel = graph
    .map(node => `export type { ${node.name} } from "./${node.name}";`)
    .join("\n");
  files.set("index.ts", `${GENERATED_HEADER}\n${barrel}\n`);
  return files;
}
