import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { checkGeneratedOwnership } from "./check-generated-ownership";

const roots: string[] = [];

function fixture(editableMember: string): string {
  const root = mkdtempSync(join(tmpdir(), "sdk-ownership-"));
  roots.push(root);
  const generated = join(
    root,
    "src/resources/students/generated/students.base.ts"
  );
  const editable = join(root, "src/resources/students/students.ts");
  mkdirSync(dirname(generated), { recursive: true });
  writeFileSync(
    generated,
    `// @generated by simtrain-sdk-generator. Do not edit.\nexport class StudentsBase { async list(): Promise<void> {} }\n`
  );
  writeFileSync(
    editable,
    `import { StudentsBase } from "./generated/students.base";\nexport class Students extends StudentsBase { ${editableMember} }\n`
  );
  return root;
}

afterEach(() => {
  for (const root of roots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
});

describe("checkGeneratedOwnership", () => {
  it.each([
    "async list(): Promise<void> {}",
    "list = async (): Promise<void> => {};",
    "get list(): unknown { return undefined; }",
  ])("rejects an editable generated-method shadow", member => {
    expect(() => {
      checkGeneratedOwnership(fixture(member));
    }).toThrow(/students\.list.*generated wire method/i);
  });

  it("allows a differently named composing helper", () => {
    expect(() => {
      checkGeneratedOwnership(
        fixture("async listActive(): Promise<void> { await this.list(); }")
      );
    }).not.toThrow();
  });

  it("rejects any, private headers, proxies, and missing generated headers", () => {
    const root = fixture("helper(value: any): void { void value; }");
    expect(() => {
      checkGeneratedOwnership(root);
    }).toThrow(/forbidden any/i);

    const proxyRoot = fixture(
      "helper(): unknown { return new Proxy({}, {}); }"
    );
    expect(() => {
      checkGeneratedOwnership(proxyRoot);
    }).toThrow(/Proxy/);

    const headerRoot = fixture("helper(): void {}");
    writeFileSync(
      join(headerRoot, "src/resources/students/generated/students.base.ts"),
      "export class StudentsBase {}\n"
    );
    expect(() => {
      checkGeneratedOwnership(headerRoot);
    }).toThrow(/ownership header/);
  });
});
